import type { Metadata } from "next";
//import "@/styles/reset.css";
import "@/styles/globals.css";
import { Providers } from "@/app/providers";
import Sidebar from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <div
            className="flex h-screen"
            style={{
              backgroundColor: "#212529", // Основной фон
            }}
          >
            <Sidebar activeItem="cartridges" />
            <main className="flex-1 overflow-auto">
              <body>{children}</body>
            </main>
          </div>
        </body>
      </Providers>
    </html>
  );
}
